---
- hosts: dbserver01
  tasks:
  - name: create empty file
    ansible.windows.win_file:
      path: D:\foo.conf
      state: touch
  - name: create empty folder
    ansible.windows.win_file:
      path: D:\folder
      state: directory
