win:
  hosts: 
    webserver01: 
      ansible_host: 192.168.1.146
    dbserver01: 
      ansible_host: 192.168.1.107
  vars:
    ansible_user: administrator
    ansible_password: 
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore


