---
- hosts: webserver01
  tasks:
  - name: Install IIS
    win_feature:
      name: "Web-Server"
      state: present
      restart: yes
      include_sub_features: yes
      include_management_tools: yes
  - name: Install Sprocket Web
    ansible.windows.win_copy:
      src: ~/nored-ansible/SprocketInstall/Web/
      dest: D:\DematicCMMS\sprocket\
  - name: Install Hangfire Web
    ansible.windows.win_copy:
      src: ~/nored-ansible/SprocketInstall/BackgroundJobService/
      dest: D:\DematicIQ\BackgroundJobService_sprocket/
 

- hosts: dbserver01
  tasks:
  - name: Install DBATools Powershell Module Database
    win_psmodule:
      name: dbatools
      accept_license: true
      state: present

  - name: Add Folder Data DB
    ansible.windows.win_file:
      path: D:\Data
      state: directory

  - name: Add Folder Logs DB
    ansible.windows.win_file:
      path: D:\Logs
      state: directory

  - name: Add Folder Backups DB
    ansible.windows.win_file:
      path: D:\Backups
      state: directory

#  - name: Install Sprocket Database (Create)
#    lowlydba.sqlserver.database:
#      sql_instance: SprocketDB
#      database: sprocket

  - name: Install Sprocket Database (Restore)
    lowlydba.sqlserver.restore:
      sql_instance: SprocketDB
      database: sprocket
      path: ~/nored-ansible/SprocketInstall/DB/Install
