---
- hosts: webserver01
  tasks:
  - name: Install Sprocket Web
    ansible.windows.win_copy:
      src: ~/nored-ansible/SprocketInstall/Web/
      dest: D:\DematicCMMS\sprocket\
  - name: Install Hangfire Web
    ansible.windows.win_copy:
      src: ~/nored-ansible/SprocketInstall/BackgroundJobService/
      dest: D:\DematicIQ\BackgroundJobService_sprocket/
 