---

- hosts: all
  vars_prompt:
    - name: ansible_user
      prompt: What is the Ansible Username?
      private: false

    - name: ansible_password
      prompt: What is the Ansible Password?
      private: true

- name: Setup Sprocket Web
  ansible.builtin.import_playbook: setupSprocketWeb.yml
- name: Setup Sprocket DB
  ansible.builtin.import_playbook: setupSprocketDB.yml
- name: Install Sprocket Web
  ansible.builtin.import_playbook: installSprocketWeb.yml 
  vars:
    ansible_user: ansible_user
    ansible_password: ansible_password
- name: Install Sprocket DB
  ansible.builtin.import_playbook: installSprocketDB.yml
