---
- hosts: webserver01
  tasks:
  - name: Install IIS
    win_feature:
      name: "Web-Server"
      state: present
      restart: yes
      include_sub_features: yes
      include_management_tools: yes

  - name: Add D:\Temp (Web)
    ansible.windows.win_copy:
      src: ~/nored-ansible/SprocketInstall/Setup/rewrite_amd64_en-US.msi
      dest: D:\DematicTemp\

  - name: Install IIS Url Rewrite
    win_package:
      path: D:\DematicTemp\rewrite_amd64_en-US.msi
      state: present

  - name: Delete Temp Folder
    ansible.windows.win_file:
      path: D:\DematicTemp
      state: absent


  - name: Add Host Entry DB
    community.windows.win_hosts:
      state: present
      canonical_name: sprocketdbserver
      ip_address: 192.168.1.107

  - name: Add Host Entry Sprocket Site
    community.windows.win_hosts:
      state: present
      canonical_name: sprocket.local
      ip_address: 127.0.0.1
