---
- hosts: dbserver01
  tasks:
  - name: Install DBATools Powershell Module Database
    win_psmodule:
      name: dbatools
      accept_license: true
      state: present

  - name: Add Folder Data DB
    ansible.windows.win_file:
      path: D:\Data
      state: directory

  - name: Add Folder Logs DB
    ansible.windows.win_file:
      path: D:\Logs
      state: directory

  - name: Add Folder Backups DB
    ansible.windows.win_file:
      path: D:\Backups
      state: directory

  - name: Copy SQL Package
    ansible.windows.win_copy:
      src: ~/nored-ansible/SprocketInstall/Setup/DacFramework.msi
      dest: D:\DematicTemp\

  - name: Install SQL Package
    win_package:
      path: D:\DematicTemp\DacFramework.msi
      state: present

  - name: Add SqlPackage to Path
    ansible.windows.win_path:
      elements:
      - C:\Program Files\Microsoft SQL Server\160\DAC\bin\

  - name: Delete Temp Folder
    ansible.windows.win_file:
      path: D:\DematicTemp
      state: absent


  - name: Firewall Rule to Allow Inbound SQL Port 1433
    community.windows.win_firewall_rule:
      name: SQL Port
      localport: 1433
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes

  - name: Set DB Data Default Path
    ansible.windows.win_powershell:
      script: |
        Set-DbaDefaultPath -SqlInstance SprocketDB -Type Data -Path D:\Data

  - name: Set DB Logs Default Path
    ansible.windows.win_powershell:
      script: |
        Set-DbaDefaultPath -SqlInstance SprocketDB -Type Log -Path D:\Logs

  - name: Set DB Backups Default Path
    ansible.windows.win_powershell:
      script: |
        Set-DbaDefaultPath -SqlInstance SprocketDB -Type Backup -Path D:\Backups

  - name: Restart SQL Server 
    ansible.windows.win_powershell:   
      script: |
        # Pulled From https://learn.microsoft.com/en-us/sql/powershell/how-to-enable-tcp-sqlps?view=sql-server-ver16
        [System.Reflection.Assembly]::LoadWithPartialName('Microsoft.SqlServer.SqlWmiManagement')

        $wmi = New-Object 'Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer' localhost

        $tcp = $wmi.ServerInstances['MSSQLSERVER'].ServerProtocols['Tcp']
        $tcp.IsEnabled = $true  
        $tcp.Alter()  

        $tcp = $wmi.ServerInstances['MSSQLSERVER'].ServerProtocols['Np']
        $tcp.IsEnabled = $true  
        $tcp.Alter()  

        Restart-Service -Name MSSQLSERVER -Force

